- ChangeLog
- examples/autocomplete.html
- examples/instantsearch+faceting.html
- examples/instantsearch+helper+excludes.html
- examples/instantsearch+helper.html
- examples/instantsearch+pagination.html
- examples/instantsearch.html
- index.js
- package.json
- src/algoliasearch.angular.js
- src/algoliasearch.helper.js
- src/algoliasearch.jquery.js
- src/algoliasearch.js
- test/spec/algoliasearch.js
- test/spec/client/initIndex.js
- test/spec/client/interface.js
- test/spec/index/interface.js
- test/spec/request-strategy/JSONP-creates-script-tags.js
- test/spec/request-strategy/only-JSONP-when-XHR-failure.js
- test/spec/request-strategy/slow-JSONP-response.js
- test/spec/request-strategy/try-dsn-first.js
- test/spec/request-strategy/uses-JSONP.js
- test/support-server/middlewares/request-strategy-uses-JSONP.js
- test/utils/create-fixture.js
- test/utils/test-xhr-call.js
BREAKING CHANGE, changed initialization from `new AlgoliaSearch()` =>
`algoliasearch()` #40
- The only exported global property is now `algoliasearch`
- `opts`:
- `dsnHost` removed, use `hosts:[dsnHost, other hosts]`
- `dsn` removed, use `hosts:[non-dsn-host, non-dsn-host]`
- `requestTimeoutInMs` renamed to `timeout`
- `method` renamed to `protocol`. Protocol should be specified as
`http:` or `https:`
- `hosts` behavior changed, when using custom hosts:
- no shuffling
- no dsn host is prepended to the list
- removed `AlgoliaExplainResults`, no obvious use ATM
- calling algoliasearch() without an applicationID or apiKey will
throw
- Helper: `new AlgoliaSearchHelper()` => `algoliasearch.helper()`,
same function signature
> new AlgoliaSearch() => algoliasearch()

- src/algoliasearch.angular.js
- src/algoliasearch.jquery.js
- src/browser.js
- src/migration-layer/index.js
- src/migration-layer/is-using-latest.js
- src/migration-layer/load-v2.js
- src/migration-layer/old-globals.js
- test/spec/old-globals.js
This will make the V3 update handle the `latest/algoliasearch.min.js`
usage.
fixes #63 
@redox @bobylito 
When manually upgrading to V3 without modifying usage:
When using `latest` version tag from jsdelivr:
> load algoliasearch V2 when jsDelivr `latest` detected

- ChangeLog
- build.sh
- package.json
- src/browser/builds/algoliasearch.angular.js
- src/browser/builds/algoliasearch.jquery.js
- src/browser/builds/algoliasearch.js
- src/browser/migration-layer/script.js
- test/spec/old-globals.js
When in this situation, the module loader would prevent the code
detecting and loading the V2 to execute.
Now fixed by prepending the migration-layer to the browserify bundle
It also removes the migration-layer code from the package managers (npm, bower) builds,
where it makes no sense to have it
> FIX: Handle module loaders + cdn.jsdelivr.net/algoliasearch/latest usage

- ChangeLog
- src/AlgoliaSearch.js
Previous was using the wrong base #74
> Fix #73 : if protocol is not http or https, default to http

- ChangeLog
- README.md
- package.json
- src/AlgoliaSearch.js
- src/IndexBrowser.js
- src/browser/builds/algoliasearch.js
- test/run-integration.js
- test/spec/common/index/browseAll/error-occurs.js
- test/spec/common/index/browseAll/no-arguments.js
- test/spec/common/index/browseAll/only-query.js
- test/spec/common/index/browseAll/only-queryParameters.js
- test/spec/common/index/browseAll/standard.js
- test/spec/common/index/browseAll/using-stop.js
- test/spec/common/index/interface.js
- test/spec/common/index/search/no-attributes.js
- test/spec/common/index/test-cases/browse.js
- test/spec/common/index/test-cases/browseFrom.js
- test/utils/get-fake-objects.js
- `browse(query, queryParameters)` now has the same signature than
search(). You can use any `query` and `queryParameters`.
- `browseFrom(cursor)` can be used as an efficient way to
continue (next page) a previous `browse()` call. All browse responses now have a `cursor` property.
- `browseAll(query, queryParameters)` can be used to get all
the content of your index
It returns an [EventEmitter](https://nodejs.org/api/events.html).
Available events:
- `result`
- `end`
- `error` (you should listen to it or it will throw)
There's also `stop()` method on the event emitter so that you can
stop browsing at any point.
fixes #101
> feat: new browse()/browseFrom()/browseAll()

- ChangeLog
- src/browser/builds/algoliasearch.angular.js
- src/browser/builds/algoliasearch.jquery.js
- src/browser/builds/algoliasearch.js
- test/spec/browser/angular.js
- test/spec/browser/jquery.js
- test/utils/compute-expected-request.js
We were not setting the right headers previously
Now setting
- accept: application/json and
- content-type: 'application/x-www-form-urlencoded' (POST)
- content-type: 'application/json' (PUT)
fixes #111
> fix: CORS simple request for all browser builds

- src/browser/builds/algoliasearch.angular.js
- test/spec/browser/angular.js
- test/template.html
This forces the Angular calls made to our API with `withCredentials` set to false (even if the user set them to true on their side, like when behind a Basic Auth)
> fix: withCredentials forced to false in Angular

- scripts/test-node
The idea is to be able to use `nvm` installed with `brew`
> If brew and nvm then use it

- src/AlgoliaSearch.js
- test/spec/common/client/set-cache.js
This allows for offline use of the search helper (e.g. in development situations) as a cache can be recorded before-hand and used if no connection is detected.
> Allow specification of cache

- src/AlgoliaSearchCore.js
- src/errors.js
- src/server/builds/node.js
- test/run-integration.js
NB: See #254 for previous discussions
This issue was caused because we do not distinguish CORS errors from DNS
resolution one and the code for incrementing the host index was moved into
the part that switches to the fallback.
Truth is that the current solution is not optimal as we are switching to
JSONP when we can't resolve the server name.
> Fix #251: increments hostIndex (host adress) on fallback

- src/AlgoliaSearchCore.js
- src/errors.js
- src/server/builds/node.js
- test/run-integration.js
- test/spec/browser/request-strategy/JSONP-fallback-per-request.js
- test/spec/browser/request-strategy/handles-JSONP-syntax-error.js
- test/spec/browser/request-strategy/no-JSONP-when-4xx.js
- test/spec/browser/request-strategy/use-JSONP-when-XHR-error.js
Before this commit, methods with no fallback support (basically every
method but search) would fail at retry if the DNS error occured before the API
client timeout.
The behavior is now:
- when a method with a fallback errors because of DNS failure we will
switch to JSONP right away
- when a method with no fallback errors because of DNS failure we will
still retry
We could use the same mechanism for both (= always try all hosts
before JSONP) but I am not confident doing this change within a patch
or minor version. We have too litle data on how blocked XHRS are
triggered (async, sync?).
fixes #250
> fix(retry): also retry on non search methods when DNS failure

- README.md
Fixed scope watcher to be compatible with AngularJS 1.4.3. Changes are backwards compatible. Expanded on code example to provide output of results to $scope via algolia.hits.
> Fix Angular results query search

- package.json
Closes #344 
[debug CHANGELOG](https://github.com/visionmedia/debug/blob/master/CHANGELOG.md)
algoliasearch-client-js users who use also debug in their app won't have anymore a duplicate debug and ms in their bundle.
> chore(deps): bump debug to 2.3.2, retract debug-ms-fix-yui-compressor

- package.json
- scripts/test-node
- src/AlgoliaSearchCore.js
- src/server/builds/node.js
- src/store.js
- test/run-browser.js
- test/run-node.js
- test/spec/common/request-strategy/active-hosts-state-shared-client-instantiations.js
- test/spec/common/request-strategy/try-active-hosts-first.js
- test/utils/create-fixture.js
This commit adds another layer of HA by remembering the last known
work host for one minute.
The cache keys are either:
- domain + appId + browser => Browser localStorage
- process/pageLoad + appId => Node.js, Browser fallback
This is still a bit raw I think, have some review.
> fix(retry strategy): Shared appId host usage, retry on first host after 1 minute

- src/AlgoliaSearchCore.js
- src/IndexCore.js
- src/buildSearchMethod.js
- src/server/builds/AlgoliaSearchServer.js
- test/spec/common/client/addAlgoliaAgent.js
- test/utils/test-method-call.js
**Summary**
Currently there is no way to specify an algolia agent at search time. The parameter `x-algolia-agent` is just ignored.
**Result**
This PR let the user specify a new Algolia agent the parameter `x-algolia-agent` (like with the REST API) and it will be appended to the ones specified with `addAlgoliaAgent`.
Fixes #493
> feat(x-algolia-agent): specify x-algolia-agent at search time

- src/buildSearchMethod.js
- test/spec/common/client/addAlgoliaAgent.js
**Summary**
The algolia agent can be set with x-algolia-agent in the parameters used with the search method. However additionalUA is more explicit.
**Result**
```js
index.search('search it', {addtionalUA: 'super search agent'});
```
This adds a `super search agent` to the `x-algolia-agent` header.
> fix(algolia agent): Fix parameter name for algolia agent

- package.json
the npm registry (and yarn, unpkg etc) use the files field to make sure that only files which are relevant to the reuser are in the package.
see <https://docs.npmjs.com/files/package.json#files>
fixes #527
> chore(package) add files property

- CHANGELOG.md
**Summary**
Because the changelog wasn't being rendered as markdown before now, we didn't notice that the indentation was being inconsistent (2, 4 and 6 spaces in the same file), and thus it wouldn't render properly. This PR fixes that, and all bullet points are now using 2 spaces for indentation, which gets rendered as proper markdown.
**Result**
good markdown rendering for all bullet points
> fix(changelog) make indentation consistent

- package.json
**Summary**
The homepage now is the GitHub repo, which is already visible by clicking the link to the `repository` field. The website offers a cleaner start than the repository.
Another factor: on Yarnpkg.com, the `homepage` is being left out, because it's the same as the repository
**Result**
The linked `homepage` is now the getting started link of the Algolia documentation.
> chore(pkg): list homepage on package.json

- test/run-integration.js
**Summary**
`if`/`then` have been renamed to `condition`/`consequence` to avoid conflicts with reserved keywords in strongly typed clients that want to enforce the Rules schema.
**Result**
This PR adapts the integration tests accordingly.
> refact(rules): Adapt to latest JSON schema for Query Rules

- src/deprecate.js
- src/deprecatedMessage.js
**Summary**
Use console.warn rather than console.log This is the same thing as Facebook uses for React, and is more visible than a simple console.log. It is [supported](https://developer.mozilla.org/en-US/docs/Web/API/Console/warn#Browser_compatibility) in IE8, so that should be fine
Slightly related to #569
**Result**
Deprecation warnings are now in yellow and marked as a warning so we can remove them with more ease later.
> feat(deprecation): use console.warn to be more visible

- src/AlgoliaSearchCore.js
- test/spec/common/client/interface.js
- test/spec/common/client/setExtraHeader.js
**Summary**
There's no way to check an extra header or remove one, so that needed to be done
**Result**
```js
client.setExtraHeader('X-cool-header','hello there');
client.getExtraHeader('X-cool-header'); //hello there
client.deleteExtraHeader('X-cool-header');
client.getExtraHeader('X-cool-header'); //undefined
```
Do I need to add more documentation for this somewhere?
cc @alexandremeunier 
closes #571
> feat(headers): add functions to remove and get extra headers

- src/Index.js
- src/IndexCore.js
- src/deprecatedMessage.js
- test/spec/common/client/interface.js
**Summary**
These methods will be served by their plural form in v4 and should thus be deprecated.
**Result**
All methods that will be removed are now deprecated, with a wiki page about them 
todo:
> chore(deprecation): add deprecation message to all methods that will be removed in v4

- src/Index.js
- src/IndexCore.js
**Summary**
The plural and singular  methods are still useful, and will be kept in v4
**Result**
methods no longer deprecated
* getObject
* addObject
* saveObject
* partialUpdateObject
* deleteObject
> chore(deprecation): remove deprecation message from singular methods

- package.json
Otherwise listing is not good: https://www.jsdelivr.com/package/npm/algoliasearch lists
https://cdn.jsdelivr.net/npm/algoliasearch@3.24.3/index.min.js for main file
> chore(build): provide jsdelivr the right file

- src/Index.js
- test/spec/common/index/interface.js
- test/spec/common/index/test-cases/deleteBy.js
**Summary**
This replaces `deleteByQuery`, as it's now an API feature
see (internal) algolia/doc#782
**Result**
new method `deleteBy` on Index, `deleteByQuery` deprecated (and ☁️ gone in v4)
> feat(deleteBy): add new deleteBy method

- src/AlgoliaSearch.js
- test/spec/common/client/test-cases/copyIndex.js
**Summary**
copyIndex accepts an optional third argument with the scope
**Result**
copyIndex can now accept a third parameter (scope) which is an array with values 'settings', 'synonyms', 'rules'. An empty array is treated as not given, since the api otherwise returns an error, and I have the feeling that this might be what people expect.
You can still have the callback as third argument if you want, or leave the third undefined and put it in the fourth position.
I added new tests with a valid array, empty array and undefined.
Wanted to test if callback is accepted on both position 3 and 4, but that seems to be quite hard, so for now I'll just let this be.
> feat(copyIndex): back-compatible add of scope

- src/Index.js
- test/run-integration.js
- test/spec/common/client/interface.js
- test/spec/common/index/interface.js
in v4 we will rework this under algoliasearch-extras with as much control as needed, similar for browseAll
**Summary**
exportSynonyms and exportRules will get all of the synonyms / rules on an index
**Result**
both implemented naively with the only way to control the flow being specifying hitsPerPage
**Test plan**
```js
index.batchRules([someRules]);
index.searchRules(hitsPerPage?: number).then(saveToFile);
// same for synonyms
```
> feat(synonyms): exportSynonyms and exportRules

- package.json
- test/run-integration.js
- yarn.lock
first commit: all in-range updates. I went through the changelogs, and they all look good. This is nice because it gives us the same situation as consumers of the package
second commit: out-of-range updates
1. didn't do debug because it bloated the bundle by .5k gz
2. browserify breaking changes were okay for us (didn't affect browser support because we don't use `Buffer` in the browser bundle)
3. agenteepalive breaking changes were good too
> Chore(deps): update all possible dependencies

- src/AlgoliaSearch.js
cc @proudlygeek
**Summary**
If no scope was given to copyIndex, an error was thrown. This was intended for cases where the scope is an empty array or something else wrong. `undefined` however is correct behaviour
**Result**
don't throw if the scope is `undefined`
> fix(copyIndex): don't throw if no scope at all is given

- src/AlgoliaSearchCore.js
This wasn't the case in the latest patch, because `withAPIKey` is not the same as `withApiKey`. I thought the bug was way worse before I selected the text and wondered why there were only two 'matches' in my editor, rather than three, which I knew was the case. Anyway, long story short, it was just a typo
fixes #647
> fix(core): make sure api key is sent as body if > 500 chars

- src/Index.js
- test/spec/common/index/test-cases/getSettings.js
cc @seafoox
**Summary**
There was no way to ask for `?advanced=1` in `getSettings`
**Result**
a first parameter to `getSettings` (with fallback to the callback) which is an object
if `advanced` is present in the object, it's added to the url
Fixes #637
This is an undocumented parameter, which has enterprise usage, which is why I didn't add it to the docblock.
> feat(getSettings): allow `advanced=1`

- src/Index.js
- test/spec/common/index/exportRules.js
- test/spec/common/index/exportSynonyms.js
**Summary**
These two errors were unnoticed, because the integration tests apparently bind everything.
**Result**
fixes #660
No more error about `this.as._jsonRequest` being undefined
> fix(exportXXX): bind the methods

- src/Index.js
- test/run-integration.js
**Summary**
in https://github.com/algolia/algoliasearch-client-javascript/commit/f91cddec5bbbb45b43aac15120723f99e5737608 accidentally a first argument was necessary.
**Result**
no more error with empty arguments
> fix(getSettings): allow empty call

- src/server/builds/node.js
Before this commit we were not listening for http network errors
that can happen once the connection is opened. Those can happen when you
have a network issue in the middle of a response.
I was able to reproduce this error by launching multiple requests and
unplugging my network altogether.
I would constantly get the infamous "zlib error" which was only an
effect of not being able to continue the response listening.
> fix(nodejs): handle network errors

- src/AlgoliaSearchCore.js
- test/run-integration.js
- test/spec/common/client/interface.js
- test/spec/common/client/searchForFacetValues.js
- test/spec/common/client/test-cases/searchForFacetValues.js
_This PR adds the top-level `client.searchForFacetValues([{ indexName, params }, ...queries])` method._
As we're going towards a more backend agnostic InstantSearch, we'd like to polish the internal JS client API to make it easier to write and understand.
With the current API, we need to initialize an index and to request SFFV on this index. This is an implementation detail that doesn't need to be exposed to our users.
Since AlgoliaSearch Transformers leverage this JS client interface to allow creation of custom backend implementations, we need to make it smoother. `searchForFacetValues()` should be at the same level as `search()`. For consistency, we also need to support multiple facet values queries (take an array of queries as parameter instead of a single query).
Right now, if you …
> feat(sffv): Add `client.searchForFacetValues()` 

- scripts/test
- src/AlgoliaSearchCore.js
- src/browser/builds/algoliasearch.angular.js
- src/browser/builds/algoliasearch.jquery.js
- src/browser/createAlgoliasearch.js
- src/reactnative/builds/algoliasearch.reactnative.js
- src/server/builds/node.js
- src/server/builds/parse.js
As reported by @vvo, `AlgoliaSearchCore.prototype.searchForFacetValues` does not work in IE11 because we rely on the native [`Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) since #677.
* Polyfill the `all()` method in each `client._promise` build
* Use `client._promise.all()` instead of `Promise.all()`
> feat: Polyfill `Promise.all()`

- src/Index.js
- test/run-integration.js
**Summary**
We discovered that by adding a new rule with an empty `objectID` field, you are actually targeting the add new record endpoint with a record ID set to `rules`. This PR makes sure we cannot add a new rule with an empty objectID. For more informations, here's the full description: https://github.com/algolia/algoliasearch-client-go/issues/397.
**Result**
Not sure the tests are good nor correctly written. I'm asking for help here.
> feat: Enforce Rule.ObjectID not to be empty

- src/Index.js
**Summary**
As discussed with @maxiloc and @julienbourdeau, the API key methods are supposed to only be implemented at the client level, not at the index level anymore. This is due to the fact that per-index keys are not available via the dashboard and we do not want users to use them anymore.
**Result**
N/A
> feat: Deprecate API keys methods on Index in favor of Client ones

- test/run-integration.js
see failure in Travis: https://travis-ci.org/algolia/algoliasearch-client-javascript/builds/374300255#L3665
This test can be skipped since really it's no problem if people get their results faster than expected.
I left the second timing test in there, since we still want the second request not to timeout
(this test is not run on PRs, so you won't really be able to see the difference in a PR)
> test(integration): skip specific test for iOS 11

- scripts/parse-build.webpack.config.js
fixes parse build, weirdly webpack is not throwing when importing an
unkown module using target node
> fix(parse): correct path to debug module

- package.json
- src/AlgoliaSearchCore.js
- src/browser/jsonp-request.js
- src/server/builds/node.js
- src/server/builds/parse.js
- test/spec/common/client/cache-request.js
- test/spec/common/client/cache-response.js
- test/spec/common/client/cache.js
**Summary**
This PR update the strategy for caching the requests. With the current implementation we cache the results when we receive the response. It means that when we perform multiple exact same requests in parallel the client will trigger multiple network requests. 
This PR introduce a different approach, we cache the promise of the requests. Now when multiple exact same requests are triggered in parallel the same promise is reused for all the requests. Only one network call can be trigger for a request.
List of the changes:
- add the `responseText` property to each `_request` implementation. The `jsonRequest` method now return an object with `{ body, responseText }` to properly resolve the cached value. It brings consistency in the `jsonRequest` response, we can now safely use both …
> feat(cache): cache the requests instead of responses

- package.json
- scripts/bundlesize
- scripts/test
**summary**
The reason is pretty simple: since we track the `dist` in GitHub, if we don't do a build before testing the build size; we are actually testing the size of the previous build, rather than the current build.
Also I realised that the `yarn test` command was not updated with previous test name changes, so did that.
The bundlesize had to be increased for the lite build, since #694 increased that size over the limit.
**results**
* fixed bundlesize tests
* fixed `yarn test`
* increased size allowance
> test(bundlesize): run build before testing size

- src/AlgoliaSearchCore.js
- test/spec/common/client/test-cases/search.js
fixes #719
**Summary**
Up until now this was added to the URL query parameters, but according to the [docs](https://www.algolia.com/doc/rest-api/search#method-param-strategy), this is a parameter in the body. Because of this, the strategy cannot work in JSONP anymore, but it also seems to never have worked in the first place, so I'm not too concerned about that.
**Result**
moved `opts.strategy` to the request body from the URL
> fix(search): add opts.strategy to request object

- src/IndexCore.js
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/610
This is documented nowhere and is beta, has an alternative with "similarQuery" search param
**Summary**
similarSearch isn't necessary
wiki link is: https://github.com/algolia/algoliasearch-client-javascript/wiki/Deprecated#indexsimilarsearchquery-callback
**Result**
the method is now deprecated, so it can be removed more safely
> chore(core): deprecate similarSearch

- src/errors.js
I'm not sure what's best between timed out or timeout. I have noticed it in https://sentry.io/share/issue/ed7798be9e8a4db28f21ec9eb8f49229/.
> Fix a small typo in the error message

- src/AlgoliaSearchCore.js
- test/spec/common/client/addAlgoliaAgent.js
The PR adds space between added agent.
**Before**
```
Algolia [...] (3.32.1);mySuperAlgoliaAgent;mySuperAlgoliaAgent with spaces
```
**After**
```
Algolia [...] (3.32.1); mySuperAlgoliaAgent; mySuperAlgoliaAgent with spaces
```
> fix(ua): add space between added agent

- src/AlgoliaSearch.js
- test/spec/common/client/interface.js
- test/spec/common/client/test-cases/restoreApiKey.js
This pull request introduces the `client.restoreApiKey` method as specified common api client specs.
This new method allows to restore a deleted API key, along with its associated rights.
Usage:
```js
var client = algoliasearch('.', '.');
client.restoreApiKey('APIKEY');
```
Fixes #742
> feat(api-keys): adds restore api key method

- .editorconfig
- .eslintrc.js
- jest.config.js
- lint-staged.config.js
- package.json
- packages/algoliasearch/src/__tests__/index.test.ts
- yarn.lock
**Summary**
This PR adds formatting and linting to the project:
- Prettier and ESLint (with the [Algolia configuration](https://github.com/algolia/eslint-config-algolia))
- EditorConfig
Linting can be performed manually. Additionally, every attempt to commit triggers linting (with Husky and lint-staged).
The idea is to ensure we don't commit anything "dirty" and avoid breaking a build because of linting errors. This reduces (if not completely removes) the need for "style" commits.
**Result**
To test this, try to:
- Add a JavaScript or TypeScript file with incorrect formatting or rule violations.
- Run `yarn lint`, this should raise errors.
- Stage the faulty file and try to commit it, this should raise errors as well.
- Run `yarn lint:fix`, this should take care of fixable issues.
> chore(lint): add linting

- src/Index.js
- test/spec/common/index/exists.js
- test/spec/common/index/interface.js
Added a method to check if the index exists
**Summary**
This is self-explanatory. It adds a method on the index to check if it exists or not. You can check the specification here https://github.com/algolia/algoliasearch-client-javascript/issues/768
**Results**
You can either call `index.exists.then( ... )` or `index.exists(function(err, content) { ... });`. It will return `true` if the index exists and `false` if we get a 404 AlgoliaSearchError. Any other errors is thrown.
> feat(index): implement index.exists method

- src/AlgoliaSearch.js
- src/errors.js
- src/server/builds/node.js
- test/spec/common/client/interface.js
- test/spec/node/get-secured-api-key-remaining-validity.js
This pull request adds `getSecuredApiKeyRemainingValidity` as specified on the api client specs.
closes #772
> feat: remaining-validity

- packages/transporter/src/Transporter.ts
This isn't per se a typo, but `retryable` is "more common" https://english.stackexchange.com/questions/364277/which-spelling-is-preferred-retriable-or-retryable
> chore(transporter): fix typo

- test/spec/common/index/findObject.js
This pull request fixes the wrong usage of `fauxjax` in the test `findObject` and fixes the CI build on the develop branch.
> chore: fix test suite breaking due bug on fauxjax

- src/server/builds/node.js
**Summary**
There's currently an issue for older node.js engines that do not support extra commas at the end of a method. 
**Result**
This method will now work for node.js clients
> getSecuredApiKeyRemainingValidity  has hanging comma, that throws error at runtime for node.js engine(s) <= 8

- src/Index.js
- test/spec/common/index/findObject.js
**Summary**
This pull request fixes an issue when people try to find and object without pagination, setting `paginate` to false,  using the `findObject` method. Without the `delete` code introduced in this pull request, the engine returns: `Unknown parameter: paginate`.
> fix: unknown parameter `paginate` within findObjects method

- packages/transporter/src/request-options.ts
- specs/fixtures/websites/algoliasearch-lite.com/index.html
- specs/fixtures/websites/algoliasearch.com/index.html
**Summary**
Array#indexOf is IE9, while Array#includes is not in any IE
**Result**
no more includes is used in source files
> chore: avoid Array#includes in bundle

- package.json
- packages/client-search/src/__tests__/unit/search-client.test.ts
- packages/client-search/src/createSearchClient.ts
- packages/client-search/src/types/SearchClient.ts
This method returns a promise, but in the default implementation, clearing the cache is actually instant, so the promises don't _need_ to be awaited.
> feat(searchClient): add clearCache method, which clears request & response caches

- packages/algoliasearch/src/types/AlgoliaSearchOptions.ts
Omit is included since TS 3.5, which is iirc over the oldest version we support.
> chore(ts): simplify WithoutCredentials

- packages/cache-browser-local-storage/src/__tests__/unit/browser-local-storage-cache.test.ts
- packages/cache-browser-local-storage/src/createBrowserLocalStorageCache.ts
fix: #997 
The access to the localStorage was being performed on the constructor of the `localStorage` driver making the `algoliasearch` function throwing the following exception:
This pull request delays the access to the localStorage to the async API provided by `get`, `set`, and `clear`, so the error can be `catch` - making the `fallbackable` driver proxy to the next driver in the chain.
https://github.com/algolia/algoliasearch-client-javascript/blob/d862a912d764655a415a9bffc25634d625ebe88d/packages/cache-common/src/createFallbackableCache.ts#L21
> fix: dom-exception on access to localStorage

- jest.config.js
- packages/client-search/src/__tests__/integration/browsing.test.ts
- packages/client-search/src/createBrowsablePromise.ts
- packages/client-search/src/methods/index/browseRules.ts
- packages/client-search/src/methods/index/browseSynonyms.ts
- packages/client-search/src/types/BrowseRequestData.ts
- packages/client-search/src/types/index.ts
This pull request addresses found problems on `browse` related methods in some edge cases:
1. When an index is too big, the browsing using `pages` is no longer available by the API giving the following error: `you should pass cursor of the current page to fetch next page`. So we adapt the browsable promise saying that when the response as a cursor, we use the cursor for browsing to the next page. ` : https://github.com/algolia/algoliasearch-client-javascript/compare/fix/browse-methods-edge-cases?expand=1#diff-dc6449cb3a3afc56b777c2dd08bb26c9R34
2. On the page related browses ( synonyms and rules ), the `hitsPerPage` wasn't sent to Algolia. Causing Algolia to send always 20 synonyms per batch, and early stop on pagination as `shouldStop: response => response.hits.length < 1000,`. …
> fix: wrong behaviour on browsing to next page/cursor in browse methods

- packages/client-analytics/src/__tests__/integration/ab-testing.test.ts
- packages/client-analytics/src/types/GetABTestsResponse.ts
This pull request fixes the `abtests` field on getAbTestsResponse.
> fix: abtests field on getAbTestsResponse

- jest.config.js
- packages/client-search/src/__tests__/integration/mcm.test.ts
- packages/client-search/src/methods/client/assignUserID.ts
- packages/client-search/src/methods/client/removeUserID.ts
Multi-cluster methods using `x-algolia-user-id` header on `POST`|`DELETE` verbs may encounter the bug `header field x-algolia-user-id is not allowed by access-control-allow-headers` while using this methods on the browser.
This PR fixes that exact same issue passing `x-algolia-user-id` on the query parameter instead of the browser.
In addition,  we also increase the timeouts of the transporter layer to avoid flakiness, and we did reactivate the mcm test now that the mcm cluster is alive again.
> fix: header field x-algolia-user-id is not allowed by access-control-allow-headers

- packages/client-search/src/__tests__/integration/settings.test.ts
This pull request sync the settings test with the current CTS.
Addresses https://github.com/algolia/algoliasearch-client-specs-internal/pull/38
> chore(missing-settings-tests): adds missing tests on settings

- packages/client-analytics/src/__tests__/integration/ab-testing.test.ts
- packages/client-common/src/__tests__/TestSuite.ts
- packages/client-search/src/__tests__/integration/api-keys.test.ts
- packages/client-search/src/__tests__/integration/copy-and-move-index.test.ts
- packages/client-search/src/__tests__/integration/mcm.test.ts
Algolia can't ensure consistency between all the 3 hosts when you perform a `waitTask` operation. For this reason, we decided to target a single host ( with bigger timeouts ) to make sure we don't have any kind of flakiness in our common test suite.
> chore(forces-single-host-on-cts): uses fixed host and fixed timeouts

- packages/client-search/src/__tests__/integration/secured-api-keys.test.ts
This pull request addresses the reuse of hosts on the secured api keys test.
> chore(fixes-secured-api-keys-test): reuses the same hosts on the test

- .gitignore
- package.json
- packages/cache-browser-local-storage/src/__tests__/unit/browser-local-storage-cache.test.ts
- packages/cache-in-memory/src/__tests__/unit/in-memory-cache.test.ts
While on local development, it might be useful to update the snapshot all the time,  on CI that could be a hidden failure.
We have two tests that updated all the time their snapshot.
On CI that looks like this:
```
Snapshot Summary
› 2 snapshots written from 2 **** suites.
Test Suites: 1 failed, 94 passed, 95 total
Tests:       1 failed, 317 passed, 318 total
Snapshots:   2 written, 1 passed, 3 total
Time:        63.027s
Ran all **** suites in 3 projects.
```
I've updated those two tests (which were using snapshots invalidly) to be inline snapshots now (could also be toEqual), and removed the .snap rule from gitignore (they're supposed to be tracked)
> test(unit): don't commit snapshots on CI

- packages/client-search/src/__tests__/integration/browsing.test.ts
- packages/client-search/src/createBrowsablePromise.ts
- scripts/prepare-test-unit.sh
Wrapping the original function in a new Promise swallowed its errors, and thus if there was some kind of error, you'd get an "unhandled promise" error like this:
```
(node:52050) UnhandledPromiseRejectionWarning: #<Object>
(node:52050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52050) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
instead of something like:
```js
{
name: 'ApiError',
message: 'Index prod_dictionaries does not exist',
status: 404, …
```
> fix(browse): expose original error from browse request

- packages/client-recommendation/src/__tests__/features/personalization-strategy.test.ts
This pull request adds personalization common tests. Addresses https://github.com/algolia/algoliasearch-client-specs-internal/pull/93.
fixes #1055
> chore(personzation-cts): adds personalization common tests

- packages/client-analytics/src/types/AnalyticsClientOptions.ts
see https://github.com/algolia/algoliasearch-client-javascript/issues/1078
This PR isn't necessary, but still will be nice for writing it, since only those two strings will be suggested
> feat(analytics): narrow the type for region

- packages/client-common/src/__tests__/TestSuite.ts
UserID could be bigger than expected resulting in a reject from the engine. We shortened it to 5 characters.
> chore(mcm): fixes user string length

- packages/client-common/src/__tests__/helpers.ts
- packages/client-search/src/__tests__/integration/get-logs.test.ts
- packages/client-search/src/types/Log.ts
Related issue: https://github.com/algolia/algoliasearch-client-javascript/issues/1137
This fixes the types of Log, as well as putting some field optionals
> fix(types): Log types

- CONTRIBUTING.md
- api-extractor.json
- packages/client-analytics/src/types/GetABTestResponse.ts
- packages/client-analytics/src/types/Variant.ts
- packages/client-analytics/src/types/VariantResponse.ts
- packages/client-search/src/types/HasPendingMappingsOptions.ts
- packages/client-search/src/types/Rule.ts
- scripts/release.sh
- add contributing guide (based on IS.js one)
- fix small error in api-extractor.json
- better link in CI comment in release script
- replace default with defaultValue: https://api-extractor.com/pages/tsdoc/tag_defaultvalue/
- put todo in separate comments so they aren't found by api-extractor
- avoid using > & {} in tsdoc comments, they can be confused with html apparently, and this looks nicer than the backslashes
> chore(release): small tweaks

- packages/client-search/src/types/SearchOptions.ts
This pull request adds the `naturalLanguages` search options.
Closes: https://github.com/algolia/algoliasearch-client-javascript/issues/1107.
> feat(natural-languages): adds option

- packages/client-search/src/types/BatchActionType.ts
Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cdffe8978f1bb97cba1e8eddb30580dd08456a54/types/algoliasearch/index.d.ts#L747-L754
> fix(batch): add missing BatchActionType

- .circleci/config.yml
**Note**: This needs to be squashed.
The CI on the build job, is currently using the latest version of node LTS: 12.18.0.
That version differs from the `nvm` lock: 12.16.2.
Due a change between 12.16.2 => 12.18.0, the CI is now displaying this error while building the bundle: `with error cannot find module @babel/compat-data/corejs3-shipped-proposals.`.
We had two solutions: 
- One is upgrade dev dependencies, but that makes the bundle size bigger. And we really don't have time to investigate this now. 🛑 
- The second one (the one used in this pull request) is lock the node version on the CI build job. ✅
> chore: fixes build error on the ci

- packages/client-search/src/__tests__/integration/browsing.test.ts
- packages/client-search/src/methods/index/browseObjects.ts
- packages/client-search/src/methods/index/browseRules.ts
- packages/client-search/src/methods/index/browseSynonyms.ts
- packages/client-search/src/types/BrowseOptions.ts
Exposing `shouldStop` allows people to create a different reason to stop browsing, e.g. if they only need the first 10.000 results instead of the whole index.
see #991 for use case examples
> feat(browse): make shouldStop public on the browsable methods

- packages/client-search/src/types/Log.ts
fixes #1108
https://www.algolia.com/doc/api-reference/api-methods/get-logs/#method-response-inner_queries
> feat(getLogs): enhance type with inner_queries

- .circleci/config.yml
Node version 14 is available since the 21/04/2020: [medium.com/@nodejs/node-js-version-14-available-now-8170d384567e](https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e)
This pull request tests this library against that version.
> chore(tests): tests against node 14

- packages/client-search/src/types/Log.ts
Hey @Ant-hem , can you confirm that the type is now correct? Including what is optional or not:
```ts
inner_queries: Array<{
index_name: string; // required
query_id?: string; // optional
offset?: number; // optional
user_token?: string; // optional
}>;
```
> fix(log-type-inner-queries): apply snake_case

- package.json
- packages/requester-node-http/src/__tests__/unit/node-http-requester.test.ts
- packages/requester-node-http/src/createNodeHttpRequester.ts
- yarn.lock
Original pull request: #1162.
Fixes: #1161 
Same pull request as the original one. Just added the readable stream dependency so this code can be tested in every node version.
> fix(requester-node-http): fix handling chunked responses fix #1161

- packages/client-search/src/__tests__/integration/rules.test.ts
- packages/client-search/src/types/Rule.ts
This pull request adds the possibility of passing multiple conditions on query rules.
Closes https://github.com/algolia/algoliasearch-client-javascript/issues/1170.
> feat: multiple conditions on query rules

- packages/client-search/src/types/Rule.ts
This pull request marks the `condition` key as deprecated, as mentioned on the issue of this feature.
Fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1170.
> feat(typescript): marks `condition` as deprecated on multiple conditions

- packages/client-recommendation/src/__tests__/features/personalization-strategy.test.ts
fixes #1178
Basically the perso API has a limit of 15 calls per day, per application, which will make all tests fail. We prepare ourselves for this now, and also accept the 429 response to be correct
> test(perso): work around limitations on setPersonalizationStrategy

- packages/requester-node-http/package.json
- packages/requester-node-http/src/createNodeHttpRequester.ts
Hey guys, today i needed call Algolia behind my entherprise proxy server.
I did not found no way to do this with this lib so I added to the createNodeHttpRequester this feature.
To use it, you need to pass the proxy url to requester option.
https://www.algolia.com/doc/api-client/advanced/configure-the-client/javascript/?language=javascript#requester
like this:
const algoliasearch = algoliasearch(
'YourApplicationID',
'YourSearchOnlyAPIKey',
{
requester: createNodeHttpRequester('http://yourproxy:8080')
},
);
> feat(createNodeHttpRequester): Add proxy support to another Agent on createNodeHttpRequester

- packages/client-search/src/types/Rule.ts
doesn't have a test yet, but allows you to base on top of this.
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1155
see: https://www.algolia.com/doc/api-reference/api-methods/save-rule/#method-param-objectids
> feat(rule): add group promotes

- packages/client-search/src/types/GetObjectsResponse.ts
Using `getObjects` returns an array of records but also `null` when the object id doesn't match any record. Updating the type to reflect that.
See example of a response where the first object id matches a record and the second (object id "z") doesn't:
> fix(getObject): null in return type for items

- package.json
- packages/transporter/src/__tests__/unit/hosts.test.ts
- packages/transporter/src/createStatelessHost.ts
- packages/transporter/src/types/HostOptions.ts
In v3 the API was `hosts: string[]`. It's easy to miss out on this in the migration guide, and it's also simpler to write just a string in the general case
fixes #1188
> feat(hosts): accept url as string

- packages/client-search/src/types/Hit.ts
- packages/client-search/src/types/MultipleQueriesResponse.ts
- packages/client-search/src/types/SearchResponse.ts
- packages/client-search/src/types/index.ts
This introduces a new generic `Hit` type that infers values for records' highlighting and snippeting results.
> feat(types): introduce generic `Hit` type

- packages/client-search/src/types/Hit.ts
- Extract and expose `RankingInfo` type
- Add missing personalization field for ranking info
> feat(client-search): add personalization field to RankingInfo

- packages/requester-node-http/src/__tests__/unit/node-http-requester.test.ts
- packages/requester-node-http/src/createNodeHttpRequester.ts
On the crawler we are trying to control more our http connections 
and we would like to modify the behavior of the client to test a few things, especially the `family` options.
This option is related to ip resolution and a "fix" to reduse some network errors like: `ENOTFOUND` `EAI_AGAIN`
Those errors are the most common ones that triggers the infamous "Unreachable hosts"
ref: https://github.com/nodejs/node/issues/5436#issuecomment-189474356
(personal opinion would be to use `family: 4` by default, DM for more about this)
If you are not confident letting people modify the whole options, we'll be fine with just the `family` option.
> fix(node): allow passing requesterOptions

- ship.config.js
basically if you don't use lerna to update the versions, internal versions get out of sync and the dependencies never get updated (even if we would run lerna version).
This PR solves that by preventing shipjs updating the versions and doing it all with lerna in versionUpdated hook
> chore(release): configure shipjs to use lerna

- packages/algoliasearch/src/__tests__/default.test.ts
- packages/algoliasearch/src/types/AlgoliaSearchOptions.ts
- packages/client-common/src/__tests__/TestSuite.ts
see https://github.com/algolia/algoliasearch-client-specs-internal/issues/144
This actually didn't need to change any code, just the types, since they didn't allow appId & apiKey, while they actually are passed along already
> feat(analytics-reco): allow creation of clients with their own credentials

- packages/algoliasearch/src/builds/browserLite.ts
- specs/answers.spec.ts
This PR exposes `findAnswers` method in the lite version. In our documents, we kind of encourage to use `algoliasearch/lite` a lot. So we'd better have this method in the lite version as well for better adoption.
> fix(findAnswers): expose in lite version

- packages/client-search/src/types/SearchResponse.ts
https://www.algolia.com/doc/api-reference/api-methods/search/#method-response-facets_stats
as far as I can tell this was always wrong in v4
> fix(ts): correct search response for facets_stats

- packages/client-search/src/types/Hit.ts
we didn't notice this earlier, since in InstantSearch.js we didn't yet update to the version of algoliasearch including the highlighting. The type in algoliasearch is better than the one in InstantSearch though, so we can find a way to switch in the future
> fix(ts): don't require every attribute to be highlighted

- packages/client-search/src/types/Indice.ts
- packages/client-search/src/types/ListIndicesResponse.ts
1. the type for createdAt & updatedAt is actually a string timestamp, not a number
2. the type should be called Index, not Indice
2. add the types for replica-related properties
see https://www.algolia.com/doc/api-reference/api-methods/list-indices/ for the reference
> fix(ts): correct type for listIndices response

- packages/client-search/src/types/SearchOptions.ts
- packages/client-search/src/types/Settings.ts
A new setting and parameter as an add-on to [decompoundedAttributes](https://www.algolia.com/doc/api-reference/api-parameters/decompoundedAttributes/?client=javascript)
see https://github.com/algolia/algoliasearch-client-specs-internal/issues/153
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1242
> feat(ts): add decompoundQuery

- packages/client-search/src/types/Settings.ts
fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1243
> feat(ts): add the attributesToTransliterate setting

- packages/transporter/src/concerns/retryDecision.ts
- packages/transporter/src/concerns/retryableRequest.ts
Warning: I'm not a JS developer so I have no idea if there might be BC-breaks in this PR or not. I also don't know if this might actually fix any bug, hence why I picked `refactor` here.
> Spell success properly

- packages/client-search/src/types/FindAnswersOptions.ts
This PR renames `params` to `searchParameters` in `FindAnswersOptions`.
`params` is still supported but the new `searchParameters` is recommended for better clarification.
Should we leave `params` and mark it as deprecated? Or just delete it since it's a type and deleting it won't affect runtime?
> fix(answers): rename params to searchParameters

- packages/client-search/src/types/MultipleQueriesQuery.ts
The engine recently added support for facet value search from the `search` and `multipleQueries` method.
This PR updates the `MultipleQueriesQuery` to reflect this change.
```ts
searchClient
.search([
{
indexName: 'instant_search',
query: 'a',
},
{
type: 'facet',
indexName: 'instant_search',
facet: 'categories',
query: 'a',
},
])
.then(({ results }) => {
console.log(results);
});
```
- [Query object documentation](https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/#method-param-query-object)
> feat(types): support `type` and `facet` in search methods

- packages/client-search/src/__tests__/integration/dictionary.test.ts
**Summary** 
In some cases, the previously generated `objectID` was matching an existing one
> fix(dictionary): generates random objectID

- packages/client-search/src/types/GetApiKeyResponse.ts
- packages/client-search/src/types/UpdateApiKeyOptions.ts
- `createdAt` is a unix timestamp when using `listApiKeys` or `getApiKey`, not a `string`
- `UpdateApiKeyOptions` is missing the `acl` attribute (See [documentation](https://www.algolia.com/doc/api-reference/api-methods/update-api-key/#method-param-acl))
> fix(api-keys): fix typing issues

- packages/client-search/src/types/Rule.ts
- packages/client-search/src/types/SearchResponse.ts
- packages/client-search/src/types/Settings.ts
DX-2066
see also the helper PR: https://github.com/algolia/algoliasearch-helper-js/pull/823
> feat(ts): document renderingContent

- packages/client-search/src/types/Rule.ts
Unless the documentation is wrong, the type should be the same.
(that also means there is no test for this use case)
> fix(Rule): automaticOptionalFacetFilters take the same input as automaticFacetFilters

- packages/recommend/src/__tests__/getFrequentlyBoughtTogether.test.ts
- packages/recommend/src/__tests__/getRecommendations.test.ts
- packages/recommend/src/__tests__/getRelatedProducts.test.ts
- packages/recommend/src/methods/getFrequentlyBoughtTogether.ts
- packages/recommend/src/methods/getRecommendations.ts
- packages/recommend/src/methods/getRelatedProducts.ts
- packages/recommend/src/types/WithRecommendMethods.ts
Before releasing the new Recommend API client, we changed the API to support multi-query on the methods. The methods only accept arrays now.
```ts
import algoliarecommend from '@algolia/recommend';
const recommendClient = algoliarecommend('appId', 'apiKey');
recommendClient
.getRelatedProducts([
{
/* ... */
},
])
.then((response) => {
console.log(response);
});
```
> feat(recommend): support multiple queries

- ship.config.js
This will avoid issues like #1286 where new packages are published as private.
We've got a similar configuration for Autocomplete: https://github.com/algolia/autocomplete/blob/e019b4dd7968f23ba500235e866e74f05fbed9de/ship.config.js#L20-L22
> chore(release): force public access on npm release

- packages/client-search/src/types/FindAnswersResponse.ts
Without this, the type is Hit[] & AnswersHit[] (paraphrased), which causes TypeScript to require extra casting to read _answer, which isn't expected.
> fix(answers): omit original hits in response

- rollup.config.js
**Summary**
The umd output name was defaulted to `algoliasearch`, since it was the only one providing an umd file. As we now have the `@algolia/recommend` package that also exposes an umd file, we need to be able to override the output name.
See [this sandbox](https://codesandbox.io/s/xenodochial-wu-tp1kl) where `@algolia/recommend` is available on the `algoliasearch` name when importing the umd file.
> fix(recommend): expose correct key on window in umd

- packages/recommend/src/__tests__/getRecommendations.test.ts
- packages/recommend/src/methods/getRecommendations.ts
**Summary**
Sending `threshold: undefined` to the API client causes the default value (`0`) to be overridden.
[sandbox reproduction](https://codesandbox.io/s/frosty-star-73kq7?file=/src/index.js)
**Result**
The default value isn't overridden when sending `threshold: undefined`
> fix(recommend): prevent `undefined` threshold

- packages/recommend/src/types/RecommendationsQuery.ts
This adds the TSDoc of the Recommend API client, based on the [existing documentation](https://www.algolia.com/doc/api-reference/api-methods/get-recommendations/).
> docs(recommend): add TSDoc

- renovate.json
Disable renovate until the CTS is in place, or some other way to make the test less flaky and able to run in parallel.
> chore: disable renovate until the test suite is less flaky

- packages/client-search/src/types/SearchOptions.ts
- packages/client-search/src/types/Settings.ts
Updating the `Settings` and `SearchOptions` types to add two reranking properties:
- enableReRanking (already existed in `SearchOptions`)
-  reRankingApplyFilter
These settings already exist on the engine for some time. They are already used in the dashboard but without these type we are building up quite a few "@ts-ignore".
> feat(types): add reranking engine settings to types

- packages/client-search/src/types/DeleteByFiltersOptions.ts
- packages/client-search/src/types/SearchOptions.ts
> fix(types): allow mix of strings and arrays in facetFilters

- packages/client-search/src/types/Hit.ts
- packages/client-search/src/types/SearchOptions.ts
- packages/client-search/src/types/Settings.ts
This is a follow up to #1378 
1. Adding `null` to the list of possible types for the `reRankingApplyFilter` search/setting option
1. Adding property `promotedByReRanking` to the `RankingInfo` type.
1. This is how we reset the filter in the dashboard, it was an oversight in the first PR.
2. Has been sent back by the engine for some time but was never added to the client's types.
> # fix(types): updating reRankingApplyFilter type and adding new property to RankingInfo

- packages/client-search/src/types/DeleteByFiltersOptions.ts
- packages/client-search/src/types/SearchOptions.ts
Correct me if I'm wrong, but I believe the fix for `facetFilters` in #1384 should apply to `numericFilters` and `tagFilters` as well.
> fix(types): allow mixed arrays in numeric and tag filters

- packages/recommend/src/types/RecommendModel.ts
Auto-merge was enabled, which skipped https://github.com/algolia/algoliasearch-client-javascript/pull/1396#discussion_r825795334
This PR move the `TrendingModel` type declaration before its usage in `RecommendModel`
> fix(recommend): declare type before usage

- packages/algoliasearch/src/__tests__/default.test.ts
- packages/algoliasearch/src/__tests__/lite.test.ts
`places` disappears in less than a month, and tests does not pass anymore, so we remove the remaining tests from the suite.
> chore: remove places tests

- packages/client-search/src/types/SearchOptions.ts
According to https://www.algolia.com/doc/api-reference/api-parameters/queryLanguages/?client=javascript, it can be sent as a search parameter too.
fixes #1405
> feat(search): add type for queryLanguages

- README.md
Ticket: https://algolia.atlassian.net/browse/APIC-576
Add `next` paragraph in the README, stating the development of the `v5` version. This allow us to redirect users and label issues accordingly.
> chore: mention `next` version in `README`

- packages/client-search/src/types/SearchOptions.ts
- Update the `SearchOptions` to include `explain` as a typed parameter for better use within the Algolia dashboard
- Adds the `explain` attribute as a `string[]` to the V4 `SearchOptions`.
- Test cases shouldn't change. The attribute is already included in a search test [here](https://github.com/algolia/algoliasearch-client-javascript/blob/master/packages/client-search/src/__tests__/integration/search.test.ts#L159)
> fix(types): Updating searchoptions with explain attribute

- packages/client-search/src/types/SearchResponse.ts
Ticket: https://algolia.atlassian.net/browse/CR-1581
Fixes https://github.com/algolia/algoliasearch-client-javascript/issues/1418
Add `abTestID` field to the `SearchResponse` type.
> fix(types): add `abTestID` to `SearchResponse`

- packages/client-search/src/types/SearchOptions.ts
This text is a mistake. `aroundRadius` is not for IP address searches
only.
Copied the text from [here](https://www.algolia.com/doc/api-reference/api-parameters/aroundRadius/).
> docs: Fix incorrect property description

- .gitignore
- packages/recommend/src/types/TrendingFacetsQuery.ts
Remove `fallbackParameters` and `queryParameters` given that the recommend API does not support these props.
🐛 : [JIRA](https://algolia.atlassian.net/browse/RECO-1173)
> fix(recommend): remove unused trendingFacets props 

- packages/client-search/src/types/Settings.ts
- Update the typing to be able to set the mode on a `setSettings` call.
> feat(neuralsearch): add mode to settings types

- packages/client-search/src/types/Settings.ts
Update the existing typing to include `semanticSearch` with `eventSources` for configuring NeuralSearch.
RFC: https://algolia.atlassian.net/wiki/spaces/NEUR/pages/4507369495/Event+Sources+for+Neural+Search
> feat(neuralsearch): adding the semanticSearch settings to client-search

- packages/client-search/src/types/Settings.ts
Explicit nullable type for the `eventSources` setting. This is helpful since the `null` state is the 'default' for the field, and nulling the value has specific behavior in the search engine (e.g. to use the primary/replica index group as event sources).
> feat(neural): make eventSources nullable

- packages/client-analytics/src/types/GetABTestsOptions.ts
Ref: https://github.com/algolia/go/pull/10733
https://algolia.atlassian.net/wiki/spaces/GR/pages/4518510769/List+A+B+test+index+variant+prefix
[SCC-443]
Updating the typing of the GET for retrieving all ab tests to add the new `indexPrefix` and `indexSuffix` query parameters to facilitate getting specific indices for the dashboard as part of the neuralsearch integration.
[SCC-443]: https://algolia.atlassian.net/browse/SCC-443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(neuralsearch): Update ab test typing for prefix and suffix retrieval

- packages/requester-fetch/src/createFetchRequester.ts
When trying to use Algolia's `requester-fetch` package combined with the `algoliasearch` method on Cloudflare workers, we get the error `The 'mode' field on 'RequestInitializerDict' is not implemented.`. For reference CF workers are ran in V8 Isolate and they have not added an implementation for mode on their fetch runtime.
Although it's not ideal that the behaviour of CloudFlare is to throw an error, we can avoid this issue by removing the mode field from the `requester-fetch` fetch options. The default mode is `cors` anyway so there is no functional change.
This issue has surfaced for multiple people as seen in [this forum](https://discourse.algolia.com/t/cloudflare-workers-and-algoliasearch-javascript-problem/16714).
I looked at the other request packages but they do not fit the bill. …
> FEAT: Removing Mode for CloudFlare Workers

- packages/recommend/src/methods/getRecommendations.ts
- packages/recommend/src/types/TrendingQuery.ts
- packages/recommend/src/types/WithRecommendMethods.ts
- packages/recommend/src/types/index.ts
As defined in `getRecommendations.ts`, a `query` is defined as `ReadonlyArray<RecommendationsQuery | TrendingQuery>` 
But in `WithRecommendMethods.ts` it seems that the definition is outdated.
Should help get the PR https://github.com/algolia/recommend/pull/131 moving.
> fix(recommend): Align `getRecommendations` type with actual implementation

- package.json
- packages/client-search/src/methods/client/updateApiKey.ts
Fix the `wait` method of the `updateApiKey` request so it really waits for an update on the key instead of directly resolving.
> fix(search): fix wait method for updateApiKey request

- package.json
- packages/cache-browser-local-storage/src/__tests__/unit/browser-local-storage-cache.test.ts
- packages/cache-browser-local-storage/src/createBrowserLocalStorageCache.ts
- packages/cache-browser-local-storage/src/types/BrowserLocalStorageCacheItem.ts
- packages/cache-browser-local-storage/src/types/BrowserLocalStorageOptions.ts
- packages/cache-browser-local-storage/src/types/index.ts
This introduces the ability to set a TTL for cached items, in order to reduce the size of this cache and prevents the cache from permanently holding onto the items.
This feature is optional, and if the `timeToLive` option is not configured, it will behave like how it currently does.
We ran into storage quotas, and saw that this cache can grow to a couple MB after a while. We made our own patched version, but it would be nice if this feature was implemented upstream.
Providing this fix in the form of a pull request was discussed via the [support.algolia.com/hc/requests/551781](http://support.algolia.com/hc/requests/551781) support ticket.
> feat(cache-browser-local-storage): Implemented TTL support to cached items

- packages/client-search/src/__tests__/integration/multiple-operations.test.ts
- packages/client-search/src/types/MultipleQueriesResponse.ts
This PR unions `SearchForFacetValuesResponse` with `SearchResponse<TObject>` as possible return types for results in the `multipleQueries` API.
The `MultipleQueriesQuery` interface [states](https://github.com/algolia/algoliasearch-client-javascript/blob/4.13.0/packages/client-search/src/types/MultipleQueriesQuery.ts#L27-L48) that you can supply either a `default` or a `facet` query. This is also confirmed by the Algolia [documentation.](https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/#method-param-type)
However, the MultipleQueriesResponse [definition](https://github.com/algolia/algoliasearch-client-javascript/blob/4.13.0/packages/client-search/src/types/MultipleQueriesResponse.ts#LL7C18-L7C32) does not include …
> fix(types): union SearchForFacetValuesResponse type for multipleQueries

- packages/client-analytics/src/types/VariantResponse.ts
This PR is a follow up from the one made in the generated clients (https://github.com/algolia/api-clients-automation/pull/1656) to allow using them in the dashboard immediately.
[SCC-671]
[SCC-671]: https://algolia.atlassian.net/browse/SCC-671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(abtests): add outlier count to variant response payload

- packages/recommend/src/__tests__/getRecommendations.test.ts
- packages/recommend/src/types/WithRecommendMethods.ts
In recommend add type `MultipleQueriesResponse` that basically reverts back to the old definition before PR https://github.com/algolia/algoliasearch-client-javascript/pull/1460
> fix(recommend): Add Type RecommendQueriesResponse from old MultipleQueriesResponse for recommend

- packages/client-search/src/types/ApiKeyType.ts
This is a follow up change to a change made in the generated clients (https://github.com/algolia/api-clients-automation/pull/1985) so it can be used the dashboard.
[AIE-512](https://algolia.atlassian.net/browse/AIE-512)
[AIE-512]: https://algolia.atlassian.net/browse/AIE-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search): add inference ACL to API key object

- package.json
- packages/client-common/src/__tests__/TestSuite.ts
- packages/recommend/src/builds/browser.ts
- packages/recommend/src/builds/node.ts
- packages/recommend/src/methods/getRecommendations.ts
- packages/recommend/src/methods/getRecommendedForYou.ts
- packages/recommend/src/methods/index.ts
- packages/recommend/src/types/RecommendModel.ts
- packages/recommend/src/types/RecommendedForYouQuery.ts
- packages/recommend/src/types/WithRecommendMethods.ts
- packages/recommend/src/types/index.ts
- playground/browser/index.html
- scripts/prepare-playground.sh
Add `getRecommendedForYou` function to recommend.
To test locally you can update `playground/browser/index.html` with the following content: 
```html 
<html>
<head>
<script src="/playground/browser/recommend.umd.js"></script>
<script>
const recommend = window['@algolia/recommend'];
const client = recommend('betaUASF0EMRRM', '2c80241f06757af6fc4ef4a2d9523b6d');
client
.getRecommendedForYou([
{
indexName: 'bestbuy',
queryParameters: {
userToken: 'user_token_1',
},
},
])
.then(({ results }) => {
console.log(results[0]);
})
.catch(err => {
console.error(err);
});
</script>
</head>
<body></body>
</html>
```
> feat(recommend): add recommended-for-you model

- packages/recommend/src/types/RecommendedForYouQuery.ts
For the model `recommended-for-you` the `userToken` parameter is not optional otherwise the API will throw an error:
> fix(recommend): RecommendedForYouQuery `userToken` should be required

- packages/recommend/src/methods/getRecommendations.ts
- packages/recommend/src/methods/getRecommendedForYou.ts
- packages/recommend/src/types/RecommendationsQuery.ts
- packages/recommend/src/types/RecommendedForYouQuery.ts
- packages/recommend/src/types/WithRecommendMethods.ts
When calling `getRecommendations` we need to make sure that the user doesn't have to pass `objectID` for the model `recommended-for-you`.
Otherwise this error will occur: 
```
Property 'objectID' is missing in type '{ indexName: string; model: "recommended-for-you"; fallbackParameters: RecommendSearchOptions | undefined; queryParameters: (RecommendSearchOptions & { ...; }) | undefined; maxRecommendations: number | undefined; }' but required in type 'RecommendationsQuery'.
```` 
The fix should be a patch since the model is not publicly available yet.
> fix(recommend): update recommended-for-you model type

- package.json
- packages/algoliasearch/package.json
- packages/algoliasearch/src/builds/browser.ts
- packages/algoliasearch/src/builds/browserLite.ts
- packages/algoliasearch/src/builds/node.ts
This PR adds methods from **algolia/recommend** methods into **algoliasearch**, allowing Algolia customers to perform both search and get recommendations with a single API client.
In detail:
- **algoliasearch/lite** only implements `getRecommendations()`
- **algoliasearch** (browser + node) implement all the currently available methods in the recommend package
[FX-2773](https://algolia.atlassian.net/browse/FX-2773)
[FX-2773]: https://algolia.atlassian.net/browse/FX-2773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(search): fetch recommendations directly from algoliasearch

- .circleci/config.yml
- package.json
- packages/algoliasearch/package.json
- packages/algoliasearch/test/module/is-cjs-module.cjs
- packages/algoliasearch/test/module/is-es-module.mjs
- packages/recommend/src/builds/browser.ts
- packages/recommend/src/builds/node.ts
In 8087b282, we import methods from `@algolia/recommend` into `algoliasearch` to give direct access to recommendations from the search client.
The CJS bundle for `@algolia/recommend` did not export the methods, only the `recommend()` method to set up a recommend client. This caused an issue in the v4.23.0 release of `algoliasearch` as it basically imported undefined methods, which prevented the correct instantiation of the search client.
This PR reexports all methods to ensure they are present when imported by `algoliasearch`.
It also tests the built algoliasearch bundles, inspired by what we have [in InstantSearch](https://github.com/algolia/instantsearch/pull/5175).
Fixes #1511
> fix(recommend): export recommend methods to use them in algoliasearch

- package.json
- packages/recommend/package.json
- packages/recommend/src/builds/browser.ts
- packages/recommend/src/builds/node.ts
- packages/recommend/test/module/is-cjs-module.cjs
- packages/recommend/test/module/is-es-module.mjs
- yarn.lock
In #1512 I exported Recommend methods in addition to the existing default function export, to allow `algoliasearch` to import them in CJS.
This causes an issue as now there are multiple exports, which means `recommend()` cannot be accessed directly and is instead available from `require('@algolia/recommend').default`.
To prevent this, the Recommend methods are now augmenting the default function export.
> [!NOTE]
> The existing version of api-extractor [does not correctly resolve type imports](https://github.com/microsoft/rushstack/issues/1050), resulting in `import('../xyz').Type` statements with relative paths that are incorrect. I updated to the fixed version and went through all 22 type declaration files. There are no meaningful changes (in some cases type imports are aliased with a …
> fix(recommend): only export default function

- packages/client-search/src/types/SearchResponse.ts
users would like to leverage this field, documented here https://www.algolia.com/doc/api-reference/api-methods/search/#method-response-servertimems, see [CR-5848](https://algolia.atlassian.net/browse/CR-5848)
it is already provided on the `next` version
[CR-5848]: https://algolia.atlassian.net/browse/CR-5848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(types): add `serverTimeMS` to search response

- packages/client-search/src/types/Settings.ts
These are types for the upcoming no-code Banner feature.
> feat(types): add `banners` in `renderingContent`

- LICENSE.md
- packages/transporter/src/__tests__/integration/with-hosts-cache-drivers.test.ts
- packages/transporter/src/__tests__/unit/stackTrace.test.ts
- packages/transporter/src/__tests__/unit/timeouts.test.ts
- packages/transporter/src/errors/createRetryError.ts
> Hey team!
The Support team is currently in a process of removing [support@algolia.com](mailto:support@algolia.com) email from all GitHub repos and updating it to link to the new ticket form. We kindly ask that you review the changes made removing references to [support@algolia.com](mailto:support@algolia.com).
Thanks!
supersede https://github.com/algolia/algoliasearch-client-javascript/pull/1517
> fix(support): redirect to ticket link

- packages/client-search/src/types/Settings.ts
Adds typing for the new `hide` property in renderingContent facet values
JIRA ticket: https://algolia.atlassian.net/browse/EMERCH-1518
> feat(types): add hide in renderingContent facet values

- packages/algoliasearch/src/__tests__/default.test.ts
- packages/algoliasearch/src/builds/browser.ts
- packages/algoliasearch/src/builds/node.ts
- packages/algoliasearch/src/ingestion.ts
- packages/algoliasearch/src/types/Ingestion.ts
- packages/client-common/src/__tests__/TestSuite.ts
closes https://github.com/algolia/algoliasearch-client-javascript/issues/1589
the build is broken because async/await were used but compatibility requires ie>=11, this aligns with the other method definition, which removes the `regeneratorRuntime` from the bundle as well
> chore: ie 11 support
