ChangeLog
src/algoliasearch.js
test/spec/client/test-cases/addUserKey.js
test/spec/client/test-cases/getLogs.js
test/spec/client/test-cases/listIndexes.js
test/spec/index/search-no-attributes.js
test/spec/index/test-cases/addObject.js
test/spec/index/test-cases/addUserKeyWithValidity.js
test/spec/index/test-cases/browse.js
test/spec/index/test-cases/getObject.js
test/spec/index/test-cases/search/params.js

This PR changes all function signatures that were not following the "callback last parameter" defacto convention.
fixes #43

Callback always last

---

ChangeLog
Parse.js
package.json
scripts/build
scripts/parse-build.webpack.config.js
src/AlgoliaSearch.js
src/server/builds/AlgoliaSearchServer.js
src/server/builds/node.js
src/server/builds/parse.js

We now have a working Parse module with the new API

Working Parse module

---

README.md

to be merged when everything is ready,
algolia/algoliasearch-client-js#46

Prepare Node.js and JavaScript merge

---

.travis.yml
ChangeLog
package.json
scripts/test-browser
test/run-browser.js
zuul.config.js

We now test on 3 browsers on travis:
- latest chrome
- latest firefox
- latest ie

test: subset of browsers for travis prs

---

.travis.yml
package.json
scripts/build
scripts/lint
scripts/test
scripts/test-browser
scripts/test-ci
scripts/test-node
scripts/test-parse-cloud
scripts/test-phantom
test/run-integration.js
zuul.config.js

+ use latest zuul modifications
+ switch from a slow build matrix to only one build
+ use only scripts/

test: faster CI

---

ChangeLog
src/AlgoliaSearch.js
test/spec/common/client/addAlgoliaAgent.js
test/spec/common/client/interface.js
test/spec/common/client/x-algolia-agent.js
test/utils/create-fixture.js

feat: add client.addAlgoliaAgent(algoliaAgent)

---

npm-shrinkwrap.json
package.json

Some dependencies were missing, this PR adds them.

fix(react-native): adds missing dependencies (needed for 0.14+) Fixes #167

---

src/AlgoliaSearch.js
test/spec/common/index/test-cases/partialUpdateObject.js

Implement `createIfNotExists` for endpoint `/1/indexes/{indexName}/{objectID}/partial`

Add createIfNotExists for partialUpdateObject

---

README.md

Updated README (prepare algolia.com's integration)

---

README.md

docs(cdn): unpkg, not unpkgr

---

src/server/builds/node.js

fix(node): do not use let

---

src/Index.js
test/spec/common/index/test-cases/setSettings.js

fix(forwardToReplicas): use and allow forwardToReplicas instead of forwardToSlaves

---

src/store.js

Before this commit we only checked for localStorage failures at:
- page load
- localStorage.setItem
While in some situations websites could erase localStorage state for the
whole page. This has happened and will now be handled.

fix(retry strategy): handle cases were localStorage fails after success

---

src/Index.js
test/spec/common/index/test-cases/partialUpdateObjects.js

Much like partialUpdateObject, allow createIfNotExists
fixes #551

fix(partialUpdateObjects): allow createIfNotExists

---

.travis.yml

Replacing the Travis API Key now it has been regenerated.
**Summary**
**Result**

chore(Travis): Update api key

---

scripts/build

docs(build): fix typo in build script

---

src/Index.js
src/IndexCore.js

same as #575, but now on develop 😓

chore(deprecation): remove deprecation message from singular methods

---

API.md

Little changes to the examples and actual naming around getObject getObjects => getPlace getPlaces.

Places API V4 proposal

---

package.json
test/run-integration.js
yarn.lock
zuul.config.js

**Summary**
IE8 always failing, which causes us to always ignore, which makes this test useless.
**Result**
Removed Zuul testing for IE8
I also removed the `browzers` dependency because it makes more sense to manage this testing inline

chore(test): remove IE8 on zuul

---

scripts/test-node

**Summary**
nvm is broken on CI
**Result**
unset npm prefix
fixes #649

chore: make nvm work

---

src/Index.js

**Summary**
simpler logic for the fallbacks
**Result**

fix(getSettings): simpler logic

---

.travis.yml
README.md
src/AlgoliaSearchCore.js
test/spec/common/request-strategy/dsn.js
zuul.config.js

**Summary**
In some cases dsn needs to be disabled, and the base url needs to be requested.
closes #675 
**Result**
A new option `dsn`, which defaults to true for when you want to disable it
```js
algoliasearch(appId, apiKey, {dsn: false});
```

feat(core): allow disabling of dsn

---

package.json

This is required for #677 to pass

ci(size): increase the limits for the Angular size slightly

---

CONTRIBUTING.md

fixes #696
I based this on the React InstantSearch Contributing and added common pitfalls I could remember off the top of my head.

docs: add Contributing

---

package.json
src/AlgoliaSearch.js
src/AlgoliaSearchCore.js
src/browser/createAlgoliasearch.js
src/createAnalyticsClient.js
test/run-integration.js
test/spec/common/client/interface.js

**Summary**
This pullrequest introduces AB Testing to the client. A new object `Analytics` was introduce to query the analytics APi.
See more details here: https://github.com/algolia/algoliasearch-client-php/pull/408
**NOTE**: Tests on analytics should be improved one day

feat(analytics): Introduce new Analytics object

---

README.md

fixes #722
**Summary**
was unclear before which api key to use for what.
**Result**
added a note to the readme before each usage to clarify admin or search api key

docs(readme): clarify which API key to use

---

CHANGELOG.md
index.js
src/AlgoliaSearch.js
src/AlgoliaSearchCore.js
src/Index.js
src/IndexCore.js
test/utils/get-fake-objects.js
test/utils/test-method-call.js

used misspell tool from
https://github.com/client9/misspell to find and
fix automatically all spelling errors

fix: spelling

---

package.json
yarn.lock

**Summary**
In order to patch the security vulnerability, i had updated debug to `^2.6.9` by running `yarn upgrade debug@^2.6.9`
**Result**
Result is in diff.

infra(debug) bump version to patch security vulnerability

---

src/browser/builds/algoliasearch.angular.js
src/browser/builds/algoliasearch.jquery.js
src/browser/builds/algoliasearchLite.js
src/browser/createAlgoliasearch.js
src/reactnative/builds/algoliasearch.reactnative.js
src/server/builds/node.js
test/spec/common/client/x-algolia-agent.js

**Summary**
Update the UA to lib (${version})

fix(ua): change the User-Agent to use the new specs lib (version)

---

src/browser/builds/algoliasearch.angular.js
src/browser/builds/algoliasearch.jquery.js
src/browser/builds/algoliasearch.js
src/browser/builds/algoliasearchLite.js
src/browser/createAlgoliasearch.js
src/reactnative/builds/algoliasearch.reactnative.js
src/server/builds/node.js
test/spec/common/client/x-algolia-agent.js

Update the user agents to match the spec:
- Node: `Algolia for JavaScript (3.32.1); Node.js (8.15.1)`
- Browser: `Algolia for JavaScript (3.32.1); Browser`
- Browser lite: `Algolia for JavaScript (3.32.1); Browser (lite)`
- AngularJS: `Algolia for JavaScript (3.32.1); AngularJS (1.6.0)`
- jQuery: `Algolia for JavaScript (3.32.1); jQuery (3.2.1)`
- React Native: `Algolia for JavaScript (3.32.1); React Native`

fix(ua): Add the Node.js version in the UA

---

README.md

This pull request addresses the update of the `readme.md` to make him simular to the other api clients at Algolia.
**Result**: https://github.com/algolia/algoliasearch-client-javascript/blob/66ed85400ccc17ec3dcf75eff0839c4bb396e04f/README.md.

docs(readme): rewrite readme

---

packages/auth/index.ts
packages/auth/package.json
packages/auth/src/Auth.ts
packages/search-client/package.json
packages/search-client/src/SearchClient.ts
packages/search-client/src/__tests__/TestSuite.ts
packages/search-client/src/__tests__/unit/search-client.test.ts

Let's discuss about this tomorrow if you have time @Haroenv.

feat: auth proposal for v4

---

packages/analytics-client/src/__tests__/integration/ab-testing.test.ts
packages/search-client/src/__tests__/integration/rules.test.ts
packages/search-client/src/methods/index/browseRules.ts
packages/search-client/src/methods/index/clearRules.ts
packages/search-client/src/methods/index/deleteRule.ts
packages/search-client/src/methods/index/getRule.ts
packages/search-client/src/methods/index/replaceAllRules.ts
packages/search-client/src/methods/index/saveRule.ts
packages/search-client/src/methods/index/saveRules.ts
packages/search-client/src/methods/index/searchRules.ts
packages/search-client/src/methods/types/AutomaticFacetFilter.ts
packages/search-client/src/methods/types/ClearRuleResponse.ts
packages/search-client/src/methods/types/Condition.ts
packages/search-client/src/methods/types/Consequence.ts
packages/search-client/src/methods/types/ConsequenceParams.ts
packages/search-client/src/methods/types/ConsequencePromote.ts
packages/search-client/src/methods/types/ConsequenceQuery.ts
packages/search-client/src/methods/types/DeleteRuleResponse.ts
packages/search-client/src/methods/types/Edit.ts
packages/search-client/src/methods/types/EditType.ts
packages/search-client/src/methods/types/Hide.ts
packages/search-client/src/methods/types/Rule.ts
packages/search-client/src/methods/types/SaveRuleResponse.ts
packages/search-client/src/methods/types/SaveRulesOptions.ts
packages/search-client/src/methods/types/SaveRulesResponse.ts
packages/search-client/src/methods/types/SearchRulesOptions.ts
packages/search-client/src/methods/types/TimeRange.ts
packages/support/src/__tests__/TestSuite.ts

This PR adds the Query rules feature to the v4 of the JS client. 
It also adds the related CTS test.
Any feedback welcome.

feat(v4) introducing query rules

---

packages/transporter/index.js

**Summary**
typo in the entry file
**Result**
typo fixed

fix(transporter): correct file name in commonjs file

---

packages/algoliasearch/src/__tests__/default.test.ts
packages/algoliasearch/src/__tests__/lite.test.ts
packages/algoliasearch/src/builds/browser.ts
packages/algoliasearch/src/builds/browserLite.ts
packages/algoliasearch/src/builds/node.ts
packages/client-analytics/src/__tests__/unit/analytics-client.test.ts
packages/client-analytics/src/createAnalyticsClient.ts
packages/client-analytics/src/types/AnalyticsClient.ts
packages/client-common/src/__tests__/TestSuite.ts
packages/client-recommendation/src/__tests__/unit/recommendation-client.test.ts
packages/client-recommendation/src/createRecommendationClient.ts
packages/client-recommendation/src/types/RecommendationClient.ts
packages/client-search/src/__tests__/unit/search-client.test.ts
packages/client-search/src/createSearchClient.ts
packages/client-search/src/types/SearchClient.ts

This is the API we have in v3, so some people might rely on this? It also makes sense to me to access it before instantiation. If you disagree, no hard feelings :)

feat(version): expose version on presets

---

packages/client-search/src/__tests__/integration/search.test.ts
packages/client-search/src/types/SearchResponse.ts

This pull request solves #798.

feat: adds explain in search response

---

packages/client-search/src/types/SearchResponse.ts

This pull request adds docs to the search response type.

feat(search-response-docs): adds docs

---

packages/client-search/src/__tests__/integration/settings.test.ts
packages/client-search/src/types/Settings.ts

feat(settings): add enablePersonalization type

---

packages/requester-node-http/src/__tests__/unit/node-http-requester.test.ts
packages/requester-node-http/src/createNodeHttpRequester.ts

fix(requester-node-http): fix handling chunked responses (#1161)

---

packages/algoliasearch/src/builds/browser.ts
packages/algoliasearch/src/builds/node.ts
packages/client-search/src/methods/index/replaceAllSynonyms.ts
packages/client-search/src/methods/index/saveSynonyms.ts
packages/client-search/src/types/SaveSynonymsOptions.ts

feat(saveSynonyms): replaceExistingSynonyms -> clearExistingSynonyms

---

packages/algoliasearch/src/builds/browser.ts
packages/algoliasearch/src/builds/browserLite.ts
packages/algoliasearch/src/builds/node.ts

This PR adds generic `<TObject>` to `findAnswers` method.

fix(findAnswers): set default for generic TObject

---

packages/client-search/src/types/Rule.ts

feat(ts): allow filters in rule condition

---

packages/client-search/src/types/SearchOptions.ts
packages/client-search/src/types/SearchResponse.ts
packages/client-search/src/types/Settings.ts

feat(ts): add virtual index parameters

---

packages/client-search/src/types/MultipleQueriesQuery.ts

Following https://github.com/algolia/algoliasearch-client-javascript/pull/1263, this PR updates `MultipleQueriesQuery` to add the type for `facetQuery` when `type: 'facet'`
```ts
searchClient
.search([
{
type: 'facet',
indexName: 'instant_search',
facet: 'categories',
params: {
facetQuery: 'a',
maxFacetHits: 5,
},
},
])
.then(({ results }) => {
console.log(results);
});
```
[ts playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDKwCGUDGALAeTBgEsIA7AZzgF44BvAKDjgHoAqd5l9uAYShYYqTHHLAA7nACOAV2BREcCSRh44mcnGABbYkspZc6uQsQA6bnHatugzABMKAGyWnFAfgBccSjCgk5ADmANyM3BxcLNZwAILOzhAS1KKG2PhwAGbQviQ6JM7YcBAARgBWwDgwlAA0cCWy8Gqo7kp4mNQwEPWoOBR+ULJVwA7FWogQslDa5KOao4E4zrIOIxqJwZQkqxpauvoy8oqW0VE8cAAqeKhb+YVQAIpHBniTzqMlqDqOqJlQEDoENcEJggilZnAANbARASaAOagQTJA1CCZzAABumngpQqVROPFsLHs …

feat(types): support `facetQuery` in `MultipleQueriesQuery`

---

packages/client-search/src/types/SearchOptions.ts

see https://github.com/algolia/algoliasearch-client-specs-internal/issues/164

feat(ts): document enableReRanking

---

CHANGELOG.md
lerna.json
package.json
packages/algoliasearch/package.json
packages/cache-browser-local-storage/package.json
packages/cache-common/package.json
packages/cache-in-memory/package.json
packages/client-account/package.json
packages/client-analytics/package.json
packages/client-common/package.json
packages/client-common/src/version.ts
packages/client-personalization/package.json
packages/client-recommendation/package.json
packages/client-search/package.json
packages/logger-common/package.json
packages/logger-console/package.json
packages/recommend/package.json
packages/requester-browser-xhr/package.json
packages/requester-common/package.json
packages/requester-fetch/package.json
packages/requester-node-http/package.json
packages/transporter/package.json

This reverts commit 9f8956c1fad0ac29c5c72dcce73d8a0ff2c31ada which was a failed release due to flakiness

chore: revert "chore: release v4.24.0 (#1528)"
